//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpBot.Resource
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int Id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string UserFirstName { get; set; }
        public string UserText { get; set; }

        public override string ToString()
        {
            return $"{Id} {IdUser} {UserFirstName} {UserText}";
        }
    }
}
